pipeline:
  identifier: Build_amitborole88_python_sample_1703854149137
  name: Build python-sample
  orgIdentifier: default
  projectIdentifier: BuildPythonharness
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: amitborole88/python-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
